# Importing Neccesary Libraries

In [13]:
import numpy as np

## Creating a random array in numpy

In [21]:
a = np.array(([202,535,960,370,206,171],
              [800,120,714,221,566,314],
              [430,558,187,472,199 ,971],
              [763,230,761,408,869,443],
              [591,513,905,485,291,376]))

## Finding out shape and size of a numpy array

In [22]:
# Q1
print(a)
print(a.shape)
print(a.size)
print(a.dtype)

[[202 535 960 370 206 171]
 [800 120 714 221 566 314]
 [430 558 187 472 199 971]
 [763 230 761 408 869 443]
 [591 513 905 485 291 376]]
(5, 6)
30
int64


## Using Indexing to extract data from a numpy array

In [23]:
# Q2
print(a[:1])
print(a[:,3:])
print(a[2,3])

[[202 535 960 370 206 171]]
[[370 206 171]
 [221 566 314]
 [472 199 971]
 [408 869 443]
 [485 291 376]]
472


## Performing mathematical operations on a numpy array

In [24]:
#Q3
print(a*1.1)
a.sum(axis=0)
a.sum(axis=1)

[[ 222.2  588.5 1056.   407.   226.6  188.1]
 [ 880.   132.   785.4  243.1  622.6  345.4]
 [ 473.   613.8  205.7  519.2  218.9 1068.1]
 [ 839.3  253.   837.1  448.8  955.9  487.3]
 [ 650.1  564.3  995.5  533.5  320.1  413.6]]


array([2444, 2735, 2817, 3474, 3161])

## Applying statistical methods to a numpy array

In [18]:
#Q4
print(a.mean())
print(np.median(a))
print(np.std(a))

print(np.argmax(a.mean(axis=1)))
print(np.argmin(a.sum(axis=0)))

487.7
457.5
252.64839203921323
3
1


## Extracting data from a numpy array by applying conditions

In [19]:
#Q5
print(a[a>800])
np.where(np.any(a<200,axis=1))

[960 971 869 905]


(array([0, 1, 2]),)

## Reshaping a numpy array

In [42]:
a.reshape(5,2,3)

array([[[202, 535, 960],
        [370, 206, 171]],

       [[800, 120, 714],
        [221, 566, 314]],

       [[430, 558, 187],
        [472, 199, 971]],

       [[763, 230, 761],
        [408, 869, 443]],

       [[591, 513, 905],
        [485, 291, 376]]])

In [43]:
## Creating another random array

In [44]:
b=np.array(([202,535,960,370,206,171,800,120,714,221,566,314,
             430,558,187,472,199 ,971,763,230]))
print(b)

[202 535 960 370 206 171 800 120 714 221 566 314 430 558 187 472 199 971
 763 230]


## Reshaping the newly created array

In [45]:
b.reshape(1,4,5)
b.reshape(-1)

array([202, 535, 960, 370, 206, 171, 800, 120, 714, 221, 566, 314, 430,
       558, 187, 472, 199, 971, 763, 230])

## Creating a list for further use in stacking in a numpy array

In [46]:
new_store=[123,456,789,101,112,678]

## Stacking the new list on our pre-existing array

In [49]:
z=np.vstack((a,new_store))
print(z)
np.shape(z)

[[202 535 960 370 206 171]
 [800 120 714 221 566 314]
 [430 558 187 472 199 971]
 [763 230 761 408 869 443]
 [591 513 905 485 291 376]
 [123 456 789 101 112 678]]


(6, 6)

## Inserting a number in a random position in our original array

In [50]:
print(np.insert(a,1,5))

[202   5 535 960 370 206 171 800 120 714 221 566 314 430 558 187 472 199
 971 763 230 761 408 869 443 591 513 905 485 291 376]


## Extracting two rows from the original array

In [51]:
h=a[0]
j=a[1]
print(h)
print(j)

[202 535 960 370 206 171]
[800 120 714 221 566 314]


## Taking dot product of the two extracted rows

In [52]:
print(np.dot(h,j))

1163300


## Taking transpose of the original array

In [53]:
print(a.T)

[[202 800 430 763 591]
 [535 120 558 230 513]
 [960 714 187 761 905]
 [370 221 472 408 485]
 [206 566 199 869 291]
 [171 314 971 443 376]]


## Creating another random array and finding out its eigen-vectors

In [54]:
d=np.array(([2,1],
            [0,1]))
print(d)
np.linalg.eig(d)

[[2 1]
 [0 1]]


EigResult(eigenvalues=array([2., 1.]), eigenvectors=array([[ 1.        , -0.70710678],
       [ 0.        ,  0.70710678]]))